---
- name: restart service {{ node_handler_id }}
  ansible.builtin.include_tasks: tasks/002-restart.yml

- name: health check {{ node_handler_id }}
  ansible.builtin.include_tasks: tasks/001-health-check.yml