---

- name: Test | Check node_binary
  ansible.builtin.fail:
    msg: "The 'node_binary' variable can't be empty!"
  when: node_binary == ''

# Enable to foce GPG signature verification
#- name: Test | Check node_binary_signature
#  ansible.builtin.fail:
#    msg: "The 'node_binary_signature' variable can't be empty and must be a URL!"
#  when: node_binary_signature == '' or not node_binary_signature.startswith('http')

- name: Test | Check node_app_name
  ansible.builtin.fail:
    msg: "The 'node_app_name' variable can't be empty!"
  when: node_app_name == ''

- name: Test | Check node_chain
  ansible.builtin.fail:
    msg: "The 'node_chain' variable can't be empty!"
  when: node_chain == '' and node_chainspec == ''

- name: Test | Check node_parachain_chain
  ansible.builtin.fail:
    msg: "The 'node_parachain_chain' variable can't be empty!"
  when: node_parachain_role != '' and node_parachain_chain == '' and node_parachain_chainspec == ''

- name: Test | Check node_role
  ansible.builtin.fail:
    msg: "The 'node_role' variable can contain only 'validator', 'boot', 'full' or 'rpc' values!"
  when: node_role == '' or node_role not in ["validator", "boot", "rpc", "full"]

- name: Test | Check node_parachain_role
  ansible.builtin.fail:
    msg: "The 'node_parachain_role' variable can contain only 'collator', 'validator' 'rpc' or 'full' values!"
  when: node_parachain_role != '' and node_parachain_role not in ["collator", "rpc", "full", "validator"]

- name: Test | Check correctness of role variables
  ansible.builtin.fail:
    msg: "You use the wrong combination of 'node_role' and 'node_parachain_role' variables!"
  when: node_role == 'validator' and node_parachain_role == 'collator'

- name: Test | Check node_app_name
  ansible.builtin.fail:
    msg: "The 'node_app_name' variable can contain only '0-9a-zA-Z_-' symbols!"
  when: node_app_name is regex('[^0-9a-zA-Z_-]+')

- name: Test | Check node_chain_backup_restoring_type
  ansible.builtin.fail:
    msg: "The 'node_chain_backup_restoring_type' variable can contain only 'gcp', 'tar' or 'none' values!"
  when: node_chain_backup_restoring_type not in ["gcp", "tar", "none"]

- name: Test | Check node_parachain_chain_backup_restoring_type
  ansible.builtin.fail:
    msg: "The 'node_parachain_chain_backup_restoring_type' variable can contain only 'gcp', 'tar' or 'none' values!"
  when: node_parachain_chain_backup_restoring_type not in ["gcp", "tar", "none"]

- name: Test | Check gcp backup
  ansible.builtin.fail:
    msg: "If you use GCP backups for the node that uses chain: {{ node_chain }}, 
    pruning state: {{ (node_pruning > 0) }}, 
    you have to set the node_chain_backup_gcp_bucket variable or the node_chain_backup_gcp_path"
  when: node_chain_backup_restoring_type == 'gcp' and node_chain_backup_gcp_bucket == '' and node_chain_backup_gcp_path == ''

  # Should just function as a warning in check mode
- name: Test | Check if node_chain_backup_force_restoring is enabled without a custom path
  ansible.builtin.fail:
    msg: |
      node_chain_backup_force_restoring is enabled without node_chain_backup_tmp_restore_path being set. 
      This could cause long downtime if the backup size is huge
  when:
    - node_chain_backup_force_restoring
    - node_chain_backup_tmp_restore_path == ''
    - ansible_check_mode
  ignore_errors: true

- name: Test | Check parachain gcp backup
  ansible.builtin.fail:
    msg: "If you use GCP backups for the node that uses parachain: {{ node_parachain_chain }}, 
    pruning state: {{ (node_parachain_pruning > 0) }}, 
    you have to set the node_parachain_chain_backup_gcp_bucket variable or the node_parachain_chain_backup_gcp_path variable"
  when: node_parachain_role != '' and node_parachain_chain_backup_restoring_type == 'gcp' and node_parachain_chain_backup_gcp_bucket == '' and node_parachain_chain_backup_gcp_path == ''

- name: Test | Check node_chain_backup_url
  ansible.builtin.fail:
    msg: "If you use tar backups, you have to set the node_chain_backup_url variable"
  when: node_chain_backup_restoring_type == 'tar' and node_chain_backup_url == ''

- name: Test | Check node_parachain_chain_backup_url
  ansible.builtin.fail:
    msg: "If you use tar backups, you have to set the node_parachain_chain_backup_url variable"
  when: node_parachain_chain_backup_restoring_type == 'tar' and node_parachain_chain_backup_url == ''

- name: Test | Check number of executions in play
  ansible.builtin.fail:
    msg: "If you execute {{ ansible_role_name }} role multiple time in one play, please set node_handler_id "
  when: ansible_play_role_names | regex_findall(ansible_role_name) | length > 1 and node_handler_id == ''
