---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: re-deploy node with wipe
    ansible.builtin.include_role:
      name: "node"
    vars:
      node_db_wipe: true
      node_parachain_db_wipe: true

  - name: Collect service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      var: ansible_facts.services['shell.service']

  - name: check service
    ansible.builtin.assert:
      that: ansible_facts.services['shell.service'].state == 'running'

  - name: Get system_health
    ansible.builtin.uri:
      url: 'http://127.0.0.1:{{ item }}'
      method: POST
      body:
        {"id":1, "jsonrpc":"2.0", "method":"system_health", "params":[]}
      body_format: json
      headers:
        Content-Type: 'application/json'
    loop:
      - 9933
      - 9943
    register: _system_health_result

  - name: Print system_health
    ansible.builtin.debug:
      msg:
        - "Relaychain: {{ _system_health_result.results[0].json }}"
        - "Parachain: {{ _system_health_result.results[1].json }}"

  - name: relay chain syncing
    ansible.builtin.assert:
      that: _system_health_result.results[0].json['result']['isSyncing']
  - name: parachain is not syncing (it is not onboarded)
    ansible.builtin.assert:
      that: not _system_health_result.results[1].json['result']['isSyncing']

  - name: Get system_syncState
    ansible.builtin.uri:
      url: 'http://127.0.0.1:{{ item }}'
      method: POST
      body:
        {"id":1, "jsonrpc":"2.0", "method":"system_syncState", "params":[]}
      body_format: json
      headers:
        Content-Type: 'application/json'
    loop:
      - 9933
      - 9943
    register: _system_syncstate_result

  - name: Print system_syncState
    ansible.builtin.debug:
      msg:
        - "Relaychain: {{ _system_syncstate_result.results[0].json }}"
        - "Parachain: {{ _system_syncstate_result.results[1].json }}"